[config]
schemaVersion = "0.1.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Lokno"
name = "PEAKSleepTalk"
description = "Allow passed out players to talk at a reduced volume after 8 seconds."
websiteUrl = "https://github.com/Lokno/PEAKSleepTalk"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/PEAKSleepTalk/release/com.github.lokno.PEAKSleepTalk.dll"
target = "plugins/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "peak", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = [ "mods", "all", "client"]
